%Bisection (Yarılama) Metodu Elektrik Devre Uyg
clc;clear all; close all;
xl=input('Alt sınırı giriniz. R_lover');
xu=input('Üst sınırı giriniz. R_uper');
tol=input('Alt sınırı giriniz. tol=');
f=@(x)(exp(-0.005*x)*cos(sqrt(2000-0.01*x^2)*0.05)-0.01);
while (f(xl)*f(xu)>0);
    disp('Girilen aralıkta kök yok, yani değerler gir');
    xl=input('Alt sınırı giriniz. xl=');
    xu=input('Üst sınırı giriniz. xu=');
end;
er=10;iter=10;
while (abs(xu-xl)>tol);
    xr=(xl+xu)/2;
    if f(xl)*f(xr)<0;
        xu=xr;
    else;
        xl=xr;
    end;
end;
fprintf('Denklemin kökü xr=%f',xr);
